# Generated by Django 3.2.9 on 2021-11-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_panel', '0002_auto_20211122_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='author',
        ),
    ]
